### ISSUE TITLE
项目无法正常跑起来

### ISSUE THREAD

**Issue by sxyseo** [suenlai/dynamic-form#1]
项目无法正常跑起来。
能否提供
    <parent>
        <groupId>com.iflytek.epdcloud</groupId>
        <artifactId>sz-edu-archive</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
此项目文件，谢谢。

**Comment by suenlai** [comment]
不好意思,干扰你了. 此为临时阶段版本管理, 马上会删掉,

**Comment by sxyseo** [comment]
原来如此，由于目前也在做动态表单，有时间能否分享下思路？

**Comment by suenlai** [comment]
我的QQ 37523065

**Comment by sxyseo** [comment]
非常感谢!
